//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlertaUsuario
    {
        public string IdUsuario { get; set; }
        public Nullable<System.DateTime> FechaUltimaAlerta { get; set; }
        public string MensajeCorreo { get; set; }
    }
}
