//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaEstado
    {
        public decimal IdTarea { get; set; }
        public int Secuancial { get; set; }
        public int IdEstado { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Observacion { get; set; }
        public string IdUsuarioModifica { get; set; }
    
        public virtual Tarea Tarea { get; set; }
    }
}
