//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea_det
    {
        public decimal IdTarea { get; set; }
        public int Secuancial { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public double NumHoras { get; set; }
        public string IdUsuario { get; set; }
        public int IdEstado { get; set; }
        public System.DateTime FechaUltimaModif { get; set; }
        public string Observacion { get; set; }
        public Nullable<double> NumHorasReales { get; set; }
        public Nullable<System.DateTime> FechaTerminoTarea { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Tarea Tarea { get; set; }
    }
}
