//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TareaEstado
    {
        public decimal IdTarea { get; set; }
        public int Secuancial { get; set; }
        public int IdEstado { get; set; }
        public string IdUsuario { get; set; }
        public System.DateTime FechaModificacion { get; set; }
        public string Observacion { get; set; }
    
        public virtual Tarea Tarea { get; set; }
    }
}
