//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Grupo_Usuario
    {
        public int IdGrupo { get; set; }
        public string IdUsuario { get; set; }
        public string Observacion { get; set; }
        public string Descripcion { get; set; }
    }
}
