//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TareaArchivoAdjunto
    {
        public decimal IdTarea { get; set; }
        public int Secuencial { get; set; }
        public string NombreArchivo { get; set; }
        public byte[] Archivo { get; set; }
        public string TipoArchivo { get; set; }
        public Nullable<decimal> IdTareaPadre { get; set; }
    }
}
