//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWGEN_001
    {
        public decimal IdTarea { get; set; }
        public int IdGrupo { get; set; }
        public string IdUsuarioAsignado { get; set; }
        public System.DateTime FechaEntrega { get; set; }
        public Nullable<System.DateTime> FechaCierreEncargado { get; set; }
        public Nullable<System.DateTime> FechaCierreSolicitante { get; set; }
        public string NombreGrupo { get; set; }
        public int EstadoActual { get; set; }
        public string AsuntoTarea { get; set; }
        public string Encargado { get; set; }
        public string Asunto { get; set; }
        public string Estado { get; set; }
        public string Solicitante { get; set; }
        public string Vencida { get; set; }
    }
}
